name: Build and Deploy Static Site

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * 0'  # Every Sunday at 18:30 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate static site
        run: python generate_static.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: output/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
